Repository redhat-beyond/Pro4U, pull requests merged in 2023-05, with the labels that each got.

#72 Updating Images model
  proImages/migrations/0002_alter_images_professional_id.py
  proImages/migrations/0002_test_data.py
  proImages/models.py
  proImages/tests/test_pro_images.py
Labels: Status/New

#70 created specific folders for static files
  static/css/style.css
  static/img/GuyBeckenstein.jpg
  static/img/IdoSinger.jpg
  static/img/IdoYekutiel.jpg
  static/img/OfirBachar.jpg
  static/img/PatrisiaKaplun.jpg
  static/img/Pro4U_logo.jpeg
  static/img/TalReinfeld.jpg
  static/img/facebook-f.svg
  static/img/instagram.svg
  static/img/linkedin-in.svg
  static/img/twitter.svg
Labels: Status/New

#64 Update reservation model and tests.py after adding client and professional models
  conftest.py
  reservation/migrations/0002_alter_appointment_client_id_and_more.py
  reservation/migrations/0002_test_data.py
  reservation/models.py
  reservation/test_appointment_model.py
  reservation/test_schedule_model.py
  reservation/test_typeof_job_model.py
  reservation/tests.py
Labels: Status/In-Progress, Mentor review

#63 Updated review App now it's synchronized with account App
  review/migrations/0001_initial.py
  review/migrations/0002_test_data.py
  review/models.py
  review/tests/__init__.py
  review/tests/conftest.py
  review/tests/test_review.py
  review/tests/test_review_manager.py
Labels: Mentor review

#111 fixing SearchHistory/tests.py
  SearchHistory/tests.py
Labels: Status/New

#101 Adding schedule timings for each professional and add tests
  Pro4U/settings.py
  Pro4U/urls.py
  reservation/forms.py
  reservation/models.py
  reservation/templates/reservation/calendar.html
  reservation/templates/reservation/schedule.html
  reservation/templates/reservation/schedule_delete.html
  reservation/templates/reservation/schedule_details.html
  reservation/test_schedule_timings.py
  reservation/urls.py
  reservation/utils.py
  reservation/views.py
  static/css/calender.css
  templates/base_reservation.html
Labels: Status/New, CoreReview-Ready

#104 Add a page of the types of jobs of a professional and add tests
  reservation/forms.py
  reservation/models.py
  reservation/templates/reservation/typeOfJob_confirm_delete.html
  reservation/templates/reservation/typeOfJob_form.html
  reservation/templates/reservation/typeOfJob_list.html
  reservation/test_typeOfJob_addList.py
  reservation/urls.py
  reservation/views.py
  static/css/base_style.css
  templates/base.html
Labels: Status/New, CoreReview-Ready

#90 Adding chatmessage template
  Pro4U/urls.py
  chatmessage/templates/chatmessage/message.html
  chatmessage/test_chatmessage.py
  chatmessage/urls.py
  chatmessage/views.py
  static/css/chat.css
Labels: CoreReview-Ready

#83 Created Pro4U homepage in landing app
  Pro4U/urls.py
  landing/migrations/0001_initial.py
  landing/templates/html/index.html
  landing/templates/landing/base.html
  landing/templates/landing/homepage.html
  landing/templates/landing/learn-more.html
  landing/tests/test_homepage.py
  landing/views.py
Labels: Status/New, CoreReview-Ready

#117 Linking landing app with Client and Professional apps
  Pro4U/urls.py
  landing/templates/landing/base.html
  landing/templates/landing/homepage.html
  landing/templates/landing/learn-more.html
  landing/tests.py
  landing/tests/test_base_navigation_bar.py
  landing/views.py
  static/img/facebook-f.svg
  static/img/instagram.svg
  static/img/linkedin-in.svg
  static/img/twitter.svg
Labels: CoreReview-Ready

#119 Adding login page and add tests
  Pro4U/settings.py
  Pro4U/urls.py
  account/forms.py
  account/templates/account/login.html
  account/tests/test_login.py
  account/urls/login_urls.py
  account/views/login_views.py
  landing/templates/landing/base.html
  reservation/templates/reservation/typeOfJob_confirm_delete.html
  reservation/templates/reservation/typeOfJob_form.html
  reservation/templates/reservation/typeOfJob_list.html
  static/css/base_style.css
  templates/base.html
Labels: CoreReview-Ready

#122 Change logic, UI and tests of schedule timings for each professional after login PR merge
  reservation/templates/reservation/calendar.html
  reservation/templates/reservation/schedule.html
  reservation/templates/reservation/schedule_delete.html
  reservation/templates/reservation/schedule_details.html
  reservation/test_schedule_timings.py
  reservation/urls.py
  reservation/views.py
  templates/base_reservation.html
Labels: CoreReview-Ready

#130 updating chat.css and message.html
  chatmessage/templates/chatmessage/message.html
  static/css/chat.css
Labels: Status/New, CoreReview-Ready, WaitingToResponse

#93 Updated review app (templates, views, etc.)
  .github/workflows/pytest.yml
  Pro4U/urls.py
  account/migrations/0001_initial.py
  account/models/client.py
  conftest.py
  review/forms.py
  review/migrations/0001_initial.py
  review/models.py
  review/templates/review/review_form.html
  review/templates/review/review_list.html
  review/tests/conftest.py
  review/tests/test_review.py
  review/tests/test_review_form.py
  review/tests/test_review_list.py
  review/tests/test_review_manager.py
  review/tests/test_review_manager_model.py
  review/tests/test_review_model.py
  review/views.py
  static/css/review_forms.css
  static/js/infinite.js
  static/js/infinite.min.js
  static/js/jquery.waypoints.min.js
Labels: CoreReview-Ready

#129 Change logic, UI and tests of the types of jobs of a professional after login PR merge
  reservation/templates/reservation/typeOfJob_confirm_delete.html
  reservation/templates/reservation/typeOfJob_form.html
  reservation/templates/reservation/typeOfJob_list.html
  reservation/test_typeOfJob_addList.py
  reservation/urls.py
  reservation/views.py
  static/css/base_style.css
  static/img/jobs.jpg
Labels: Status/New, CoreReview-Ready, WaitingToResponse

#125 Fixed logged in users problem from the previous landing app PR
  Pipfile
  Pipfile.lock
  landing/templates/landing/base.html
  landing/templates/landing/homepage.html
  landing/templatetags/custom_tags.py
  landing/tests/test_base_navigation_bar.py
  landing/tests/test_homepage.py
  landing/tests/test_learn_more.py
  landing/views.py
Labels: CoreReview-Ready, WaitingToResponse
